### ISSUE TITLE
An error when using a quick key combination

### ISSUE THREAD

**Issue by Expertium** [tvhong/incremental-reading#1]
**Describe the bug**
In options -> Quick Keys my key combination is set to Alt+X. When I press it while reviewing my incremental reading cards (to create clozes) it gives me an error.

**To Reproduce**
1. Go to the deck where you have extracts from the web
2. Press the quick key combination while reading your extracts to make clozes
3. See error

**Expected behavior**
I should be able to make clozes without this error.

**Specs (please complete the following information):**
 - OS: Windows 10
 - Anki Version: 2.1.48
 - Incremental Reading Version: whichever is here https://ankiweb.net/shared/info/999215520 as of 16.08.2022

**Additional context**
Debug info:

Anki 2.1.48 (fb07bad3) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2022-08-15 21:06:13

Caught exception:
Traceback (most recent call last):
  File "aqt\webview.py", line 541, in handler
  File "C:\Users\user\AppData\Roaming\Anki2\addons21\999215520\text.py", line 72, in <lambda>
    'getHtmlText()', lambda text: self.create(text, settings)
  File "C:\Users\user\AppData\Roaming\Anki2\addons21\999215520\text.py", line 106, in create
    highlight = self._editExtract(newNote, did, settings)
  File "C:\Users\user\AppData\Roaming\Anki2\addons21\999215520\text.py", line 160, in _editExtract
    addCards.deckChooser.setDeckName(deckName)
AttributeError: 'DeckChooser' object has no attribute 'setDeckName'
![image](https://user-images.githubusercontent.com/83031600/184836875-8fb66448-b7a5-4922-8b9b-00e7ac2f6075.png)

**Comment by tvhong** [comment]
I think this is fixed with https://github.com/tvhong/incremental-reading/pull/5 . Can you try again with "Incremental Reading v4.11.1 (unofficial clone)" or later?
