### ISSUE TITLE
Images from Wikipedia aren't displayed properly

### ISSUE THREAD

**Issue by Expertium** [tvhong/incremental-reading#10]
**Describe the bug**
Images from Wikipedia aren't displayed properly in Anki.

**To Reproduce**
1. Press Alt+3 to import a Wikipedia article.
2. Review it
3. See that images aren't visible

**Expected behavior**
Images should be visible.

**Screenshots**
![image](https://user-images.githubusercontent.com/83031600/192008126-921fde8d-ec19-4636-ab6e-007dd1bc3f87.png)
![image](https://user-images.githubusercontent.com/83031600/192008139-7603ce10-4e75-4581-9f79-cd8b8e0faab1.png)

**Specs (please complete the following information):**
 - Windows 10
 - Anki ⁨2.1.48 (fb07bad3)⁩, Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
 - Incremental Reading Version v4.11.2

**Additional context**
I tried non-Wikipedia articles and this issue is rather inconsistent - it seems to affect all images on Wikipedia, but images from other websites are sometimes displayed properly, and sometimes aren't.

**Comment by tvhong** [comment]
Another example: https://bdtechtalks.com/2022/11/07/google-generative-ai-strategy/

**Comment by tvhong** [comment]
This should be fixed in the code now. I'll release it in version v4.11.5.

<img width="651" alt="Screenshot 2023-02-19 at 10 33 50 PM" src="https://user-images.githubusercontent.com/3963702/220030428-d85be351-97ce-49df-b8e9-2fde865fab80.png">
