### ISSUE TITLE
The most recent version (v4113) doesn't work

### ISSUE THREAD

**Issue by Expertium** [tvhong/incremental-reading#11]
**Describe the bug**
Anki won't launch with this add-on.

**To Reproduce**
1. Turn Anki on with this add-on enabled
2. See the error message

**Screenshots**
![1](https://user-images.githubusercontent.com/83031600/192735826-e5fc5a88-edd3-4c94-8c09-e113e9745138.png)

**Specs (please complete the following information):**
 - OS: Windows 10
 - Anki Version ⁨2.1.48 Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
 - Incremental Reading Version v4113

**Comment by tvhong** [comment]
Oh.. you might need a newer version of Anki.

I removed some deprecated methods from older version of Anki in the latest version.

`isMac` -> `is_mac` for example.

https://github.com/ankitects/anki/blob/88b3a8bd12b8d3c835a12cb95a05d6fc076d830c/qt/aqt/utils.py#L1242-L1243
