### ISSUE TITLE
An error when using arrow keys to scroll

### ISSUE THREAD

**Issue by Expertium** [tvhong/incremental-reading#2]
**Describe the bug**
I have absolutely no idea why, but for some reason this add-on breaks scrolling using arrow keys.

**To Reproduce**
1. Review any card
2. Press ↑ or ↓ on your keyboard
3. See error

**Specs (please complete the following information):**
 - OS: Windows 10
 - Anki Version: 2.1.48

**Additional context**
Debug info:

Anki 2.1.48 (fb07bad3) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2022-08-15 21:06:13

Caught exception:
Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Anki2\addons21\999215520\view.py", line 141, in lineUp
    currentPos = self.settings['scroll'][str(mw.reviewer.card.id)]
KeyError: '1660390043852'

**Comment by tvhong** [comment]
Thanks for the bug report!

I can reproduce it for any non-IR3 cards.

Taking a look at this. Might take sometime as I'm still familiarizing myself with Qt and Anki add-ons development.

**Comment by tvhong** [comment]
I fixed this issue in https://github.com/tvhong/incremental-reading/pull/4 . Please try to install the latest version on https://ankiweb.net/shared/info/999215520 .
