### ISSUE TITLE
Highlights are hardly readable in darkmode

### ISSUE THREAD

**Issue by zefanja** [tvhong/incremental-reading#33]
**Describe the bug**
If you use Anki with a dark theme, highlighted text is hardly readable (yellow highlight with white text).

**To Reproduce**
* enable dark mode
* open a card with a highlight

**Expected behavior**
* text color should be adjusted according to dark / light mode.

**Screenshots**
![grafik](https://github.com/tvhong/incremental-reading/assets/708888/c7174a5f-2c1f-4e2b-b756-ce1c3fa12f68)

**Specs (please complete the following information):**
 - OS: Ubuntu 22.04
 - Anki Version 23.12.1
- Incremental Reading Version v4.11.9

**Additional context**
* possible fix: https://docs.ankiweb.net/templates/styling.html?highlight=night%20mode#night-mode

**Comment by tvhong** [comment]
Thank you for reporting!

The highlight color can be configured in the addon's settings. You can try that first to see if it fixes the problem.

<img width="661" alt="image" src="https://github.com/tvhong/incremental-reading/assets/3963702/4907048d-7787-41c5-b0e6-3873fd98451a">

Maybe I can change the default color to one that works with both light and dark modes.

**Comment by zefanja** [comment]
Thank you. I think I can find a color that works both with black and white text (that's the issue, that the text changes to white in dark mode).
