### ISSUE TITLE
cant extract text

### ISSUE THREAD

**Issue by cindynap** [tvhong/incremental-reading#9]
**Describe the bug**
When I tried to extra some text

**To Reproduce**
select the text, hold and press X

Debug info:
Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 5.15.2 PyQt 5.15.5
Platform: Windows 10
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2022-09-16 00:06:29

Caught exception:
Traceback (most recent call last):
  File "aqt.webview", line 568, in handler
  File "C:\Users\cindy\AppData\Roaming\Anki2\addons21\999215520\text.py", line 68, in <lambda>
    'getPlainText()', lambda text: self.create(text, settings)
  File "C:\Users\cindy\AppData\Roaming\Anki2\addons21\999215520\text.py", line 131, in create
    highlight = self._editExtract(newNote, did, settings)
  File "C:\Users\cindy\AppData\Roaming\Anki2\addons21\999215520\text.py", line 156, in _editExtract
    addCards.rejected.connect(self.undo)
AttributeError: 'AddCards' object has no attribute 'rejected'

**Expected behavior**

**Screenshots**

**Specs (please complete the following information):**
 - OS: [Windows10]
 - Anki Version [Version ⁨2.1.54 (b6a7760c)⁩]
- Incremental Reading Version [v4111]

**Additional context**

**Comment by tvhong** [comment]
Oh.. I fixed this a few days ago (https://github.com/tvhong/incremental-reading/pull/5) but looks like I published the wrong zip file.

I just republished version 4.11.2. Can you try again?

**Comment by cindynap** [comment]
It's good now. Thanks

Regards
Cindy


Vy Hong ***@***.***> 于2022年9月18日周日 01:10写道：

**Comment by cindynap** [comment]
By the way I don't know if this is too much to ask...that would it possible
to have incremental reading add on for AnkiDroid?

Maybe start with 2 simple functions such as queue management and extra
selected text...



Vy Hong ***@***.***> 于 2022年9月18日周日 上午1:10写道：

**Comment by tvhong** [comment]
> By the way I don't know if this is too much to ask...that would it possible to have incremental reading add on for AnkiDroid?

Unfortunately no. The desktop add-on still has lots of rooms to improve, it doesn't really make sense to support another OS at this time.
